spring:
  application:
    name: helloEureka
    
server:
  port: 8761
  
eureka:
  server:
    enableSelfPreservation: false
    eIPBindRebindRetries: 0
    eIPBindingRetryIntervalMs: 2147483647
    eIPBindingRetryIntervalMsWhenUnbound: 2147483647
  instance:
    hostname: localhost
  client: 
    registerWithEureka: false
    fetchRegistry: false
